export * from "./Nav/Nav";
export * from "./Hero/Hero";
export * from "./Services/Services";
export * from "./Strategy/Strategy";
export * from "./Team/Team";
export * from "./Projects/Projects";
export * from "./Testimonials/Testimonials";
export * from "./FAQs/FAQs";
export * from "./Footer/Footer";
